install.packages("forecast")
library(readxl)
library(forecast)
data<- read_xlsx("C:\\Users\\MAHIMA\\Downloads\\sample_superstore_subset.xlsx")
getwd()
setwd("C:\\Users\\MAHIMA\\Downloads")
View(data)
attach(data)
tsdata<- ts(data$`Product Category`,frequency = 52, start = c(08-07-2010,1))
plot(tsdata)

